### Multivariate Regression

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
%matplotlib inline

In [2]:
df=pd.read_csv('homeprices.txt')

In [3]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

There is a missing value so filling it with the median of the column/feature

In [5]:
df.bedrooms.median()

4.0

In [6]:
import math

In [8]:
math.floor(3.5)

3

In [9]:
math.ceil(3.5)

4

In [10]:
bedrooms_median=math.floor(df.bedrooms.median())
bedrooms_median

4

In [11]:
df.bedrooms=df.bedrooms.fillna(bedrooms_median)

In [12]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [13]:
#creating the linear regresion object
reg=linear_model.LinearRegression()

In [15]:
X=df.drop('price',axis=1)
X

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [17]:
y=df.price
y

0    550000
1    565000
2    610000
3    595000
4    760000
5    810000
Name: price, dtype: int64

In [18]:
#training the model
reg.fit(X,y)

LinearRegression()

**Predicting the values   3000sqft,3 bedrooms,40 year old house**

In [21]:
p1=reg.predict([[3000,3,40]])
p1

array([498408.25158031])

**2500sqft 4 bedrooms and 5 year old house**

In [22]:
p2=reg.predict([[2500,4,5]])
p2

array([578876.03748933])

**Coefficients and intercept**

In [27]:
coef=reg.coef_
coef

array([  112.06244194, 23388.88007794, -3231.71790863])

In [28]:
intercept=reg.intercept_
intercept

221323.00186540443

**formula

In [32]:
p1f=(np.array([112.06244194, 23388.88007794, -3231.71790863])*np.array([3000,3,40])).sum()
p1f=p1f+intercept
p1f

498408.25157402444